### ISSUE TITLE
skipServe command line params

### ISSUE THREAD

**Issue by andreacaldera** [marksandspencer/nx-plugins#20]
## Describe the bug

Override `skipServe` with command line param

## To reproduce

Steps to reproduce the behaviour:

1. Run e2e-test with --skipServe (or something like that
2. skipServe from config is not overridden with command line params

## Expected behaviour

`skipServe` from config should be overridden with command line params
The same could be applicable to other config params?

**Comment by ludicast** [comment]
added `skipServe` with a few others to PR #22 @andreacaldera .  Hopefully that config is all that's needed for it (there's already a check for it in start-dev-server) :man_shrugging: .
