### ISSUE TITLE
let folks know you have this plugin

### ISSUE THREAD

**Issue by ludicast** [marksandspencer/nx-plugins#30]
from reading the room, there seems to be a broader move from cypress/puppeteer to playwright.

in order to let folks know about this plugin, it might be useful to mention it in the following places:

- nrwl/nx slack (there is a `#nx-plugins` channel where folks mention cool plugins)
- the [plugins directory](https://nx.dev/community)
- a comment on the [youtube video](https://www.youtube.com/watch?v=7ApphAma11A) that the official nx channel made a few days ago .  They crash-course playwright and the only comment is actually a q about a plugin!

I can do any of these for you if you like, but don't want to step on toes of course :)

**Comment by mcalthrop** [comment]
Thanks @ludicast!

We've added your suggestion to our backlog, and will get to it as soon as we can 😄

**Comment by ludicast** [comment]
cool - apparently this is the template to submit your plugin if ya'll wanted : https://github.com/nrwl/nx/blob/master/.github/PULL_REQUEST_TEMPLATE/COMMUNITY_PLUGIN.MD

**Comment by ludicast** [comment]
fyi @mcalthrop / @andreacaldera - seems there's now 2 playwright plugins in the directory: https://nx.dev/community

if you want this plugin to be used externally - so the community can use/enjoy your hard work - you probably should jump on this

(and if you only care about internal usage, you probably should set this repo private :))

**Comment by andreacaldera** [comment]
Thanks @ludicast 
We did create a PR on NX to add this to their community https://github.com/nrwl/nx/pull/12458
We are taking to NX and trying to get in but if you liked this plugin it'd be good to get a shout out from you ;-)

**Comment by andreacaldera** [comment]
@ludicast the plugin has been added to NX community, thanks for your support!!
