### ISSUE TITLE
Implement semantic versioning

### ISSUE THREAD

**Issue by aamir-mns** [marksandspencer/nx-plugins#31]
At the moment we have to manually update the version in package.json file.
Figure out which package.json file we need to update (there are 2 at the moment. One on the root level and one in each package)
When someone forks the project, the checks it runs to check the current version doesn't work.

**Comment by ludicast** [comment]
since nrwl took over lerna stewardship it might be a decent option for versioning. lerna is used alongside nx in many repos (nx itself and storybook come to mind, as well as others I've used).  gives you a way to keep the package bumping apart from the package code (mostly `lerna publish` & done).

**Comment by ludicast** [comment]
added #42 to spike out incorporation of lerna, which would intelligently update package numbers.  would require a pair of :eyes: to make sure the publishing process is smooth.

**Comment by andreacaldera** [comment]
Closing as stale
