### ISSUE TITLE
Add option to specify which package manager (npm/yarn/pnpm) to use to run tests in playwright plugin

### ISSUE THREAD

**Issue by gushogg-blake** [marksandspencer/nx-plugins#34]
Make the package manager used by the playwright executor a config option. Currently it's hardcoded to yarn so won't work if users are using npm or pnpm.

**Comment by ludicast** [comment]
added note in your PR - I wonder if abstracting to import/require playwright it in the style of cypress: https://github.com/nrwl/nx/blob/master/packages/cypress/src/executors/cypress/cypress.impl.ts#L13 would sidestep this issue

**Comment by niklissad** [comment]
it's very strange that I can't set an NPM package manager 
Also it will be great to use such package manager as in NX workspace

`"cli": {
    "packageManager": "npm"
  },`

**Comment by niklissad** [comment]
@andreacaldera thx, it works for me, now I have another issue, playwright didn't launch but it doesn't related to this issue

anyway it will be great to get package manager from NX config by default

**Comment by andreacaldera** [comment]
Closing as stale
