### ISSUE TITLE
let workflows be runnable by previous contributors

### ISSUE THREAD

**Issue by ludicast** [marksandspencer/nx-plugins#40]
![Screenshot from 2022-08-28 05-06-10](https://user-images.githubusercontent.com/18283/187066444-2d959e4f-c2b6-44fe-8bed-3e07cb6ebfa2.png)

this says "first-time", which is fair.  but otherwise considerable PR friction is added.

**Comment by andreacaldera** [comment]
Sorry I neglected this for so long @ludicast  :(
It looks like this was configured incorrectly and should now be fixed.

I'll keep an eye on it to verify it's working correctly.

**Comment by andreacaldera** [comment]
Update, it doesn't look like this is working :( Will check
