### ISSUE TITLE
Consolidate versions of playwright and @playwright/test

### ISSUE THREAD

**Issue by mcalthrop** [marksandspencer/nx-plugins#41]
## Problems

- the versions of `playwright` and `@playwright/test` are defined in two locations, are different in each location, and must be manually maintained:
  - `package.json`
  - `packages/nx-playwright/src/generators/init/generator.ts`
- the `packages/nx-playwright/src/generators/init/generator.ts` file mutates the consumer's `package.json` file when the generator is run
  - it seems a brittle approach to update the consumer's `package.json` file – it would be good to avoid this if possible
  - it would be easy to forget to update the `playwright` and `@playwright/test` versions when the root ones are updated
  - we should be able to resolve this issue by specifying those packages in the `peerDependencies` section of either `package.json` or `packages/nx-playwright/package.json` (to be determined)

## Tasks

- [ ] Investigate how best to solve the above issues
- [ ] Implement solution

## Reminder

Update private repos that are affected by these changes.

**Comment by andrew-me** [comment]
I have a branch for this here https://github.com/marksandspencer/nx-plugins/tree/consolidate-playwright-versions
Am waiting for https://github.com/marksandspencer/nx-plugins/pull/55 (which bumps the nx version) before creating a PR for this one.
