### ISSUE TITLE
unable to run the internal command of playwright

### ISSUE THREAD

**Issue by BalajiArun004** [marksandspencer/nx-plugins#63]
Hey guys I'm new to playwright and I have configured multiple projects in the playwright each project will have a different baseurl but when I try to integrate with nx whenever I try --project local returns an error Cannot find project 'local' but I have configured it in the playwright config 

`CMD :  yarn e2e <PROJECTNAME>  --project local`
playwright.config.ts
```
import type { PlaywrightTestConfig } from '@playwright/test';
import { baseConfig } from '../../playwright.config.base';
import { devices } from '@playwright/test';
const config: PlaywrightTestConfig = {
  ...baseConfig,
  testDir: './tests',
  projects: [
    {
      name: 'local',
      use: {
  ...devices['Desktop Chrome'],
        baseURL: 'http://localhost:4200'
      }
    }
  ]
};
```
playwright.config.base.ts
```
import { PlaywrightTestConfig } from '@playwright/test';
export const baseConfig: PlaywrightTestConfig = {
  retries: 3,
  maxFailures: 2,
  timeout: 120000
};

```

**Comment by Danphillipz** [comment]
@andreacaldera I've tested and this has been fixed by #76
