### ISSUE TITLE
Executor not handling 1 exit code from Playwright

### ISSUE THREAD

**Issue by Danphillipz** [marksandspencer/nx-plugins#72]
Plugin version: "@mands/nx-playwright": "0.1.26"
Playwright version: "playwright": "1.26.0"

When a playwright test fails using the `nx e2e <app-name>-e2e` command I would expect the playwright output to be logged to the console in a normal fashion, below is an example of "normal" output from playwright 

```
Running X tests using X workers

  ✓  3 [chromium] › src\example.spec.ts:23:3 › Playwright example tests @example-playwright › Console output should be retained (7s)

  X skipped
  X passed (55s)
Done in 56.75s.

```
However, I am noticing that whenever a single test fails that this is not the case, instead we see that all playwright output is logged in the following format as the playwright test command is returning a 1 exit code for failure:
![image](https://user-images.githubusercontent.com/38911348/213682414-cbd22cd0-698c-405b-ad03-260c315267cf.png)

Looking at the executor, I can see that the code is not running past the following line:
`const { stdout, stderr } = yield (0, util_1.promisify)(child_process_1.exec)(command);`

Instead, as a 1 exit code is being returned from playwright, I'm assuming the promisify call is being rejected, therefore meaning we go straight to the catch block where `console.error('Unexpected error', error);` is ran, resulting in the errors being logged into the console as seen above. 

## To reproduce

1. Use the @mands/nx-playwright generator to add playwright to your project
2. Run a single test through the @mands/nx-playwright executor where you would expect that test to fail

## Expected behaviour

1. For a failed test, the code should not fall into the 'catch' block, only going into that block for errors unrelated to test failure
2. Formatting of any playwright output should be retained and logged to the console in a normal fashion.

**Comment by Danphillipz** [comment]
If anyone could take a look at this please, that would be great. I suggest the following change to the executor which should allow the playwright output to be captured/reported correctly 
`import { ExecutorContext } from '@nrwl/devkit';
import { exec } from 'child_process';
import { startDevServer } from './lib/start-dev-server';
import executorSchema from './schema.json';
import { PlaywrightExecutorSchema } from './schema-types';

const PASS_MARKER = 'PLAYWRIGHT_PASS';

function getFlags(options: PlaywrightExecutorSchema): string {
  const headedOption = options.headed === true ? '--headed' : '';
  const passWithNoTestsOption = options.passWithNoTests === true ? '--pass-with-no-tests' : '';
  const browserOption = options.browser?.length ? `--browser=${options.browser}` : '';
  const reporterOption = options.reporter?.length ? `--reporter=${options.reporter}` : '';
  const timeoutOption = options.timeout !== undefined ? `--timeout=${options.timeout}` : '';
  const grepOption = options.grep !== undefined ? `--grep=${options.grep}` : '';
  const grepInvertOption =
    options.grepInvert !== undefined ? `--grep-invert=${options.grepInvert}` : '';

  const flagStrings = [
    headedOption,
    browserOption,
    reporterOption,
    timeoutOption,
    grepOption,
    grepInvertOption,
    passWithNoTestsOption,
  ].filter(Boolean);

  return flagStrings.join(' ');
}

export default async function executor(
  options: PlaywrightExecutorSchema,
  context: ExecutorContext,
) {
  await startDevServer(options, context);
  const flags = getFlags(options);
  const runnerCommand = options.packageRunner ?? executorSchema.properties.packageRunner.default;
  const path = options.path ?? executorSchema.properties.path.default;

  const command =
    `${runnerCommand} playwright test ${path} --config ${options.e2eFolder}/playwright.config.ts ${flags} && echo ${PASS_MARKER}`.trim();

  console.debug(`Running ${command}`);

  const success = await new Promise<boolean>((resolve, reject) => {
    exec(command, (error, stdout) => {
      console.info(`Playwright output ${stdout}`);
      if (error) {
        reject(error);
      }
      resolve(stdout.trim().includes(PASS_MARKER));
    });
  });
  return { success };
}
`

**Comment by andreacaldera** [comment]
Thanks for submitting this @Danphillipz. This is something that has been on our radar too but haven't got around doing yet. Do you mind creating a PR for this please?

**Comment by jrltt** [comment]
Hello there, I've got a similar issue in my project, but how I "solved" was running the application in parallel with the execution of Playwright. Doing this, I got a success message like this:
```bash
> nx run host-e2e:e2e

Running npx playwright test src --config apps/host-e2e/playwright.config.ts  && echo PLAYWRIGHT_PASS
Playwright output 
Running 1 test using 1 worker

  ✓  1 src/app.spec.ts:3:5 › should start page (999ms)


  1 passed (1.9s)
PLAYWRIGHT_PASS

 ————————————————

 >  NX   Successfully ran target e2e for project host-e2e (4s)
 ```
 So I wonder if this issue is related to the triggering of the application, I didn't have enough time to review more in the deep the plugin, but if this would help someone, I hope so...

**Comment by Danphillipz** [comment]
@andreacaldera Will look at getting a PR raised, may need to do something different to my suggestion as the unit tests are failing.
@jrltt Yes I am running the tests in the same way as yourself, what you have seen it correct for a positive journey (no test failures), it's upon test failure where you run into the bug
