### ISSUE TITLE
Playwright executor - Screenshots are not being generated using toHaveScreenshot or toMatchSnapshot

### ISSUE THREAD

**Issue by ealejandrootalvaro** [marksandspencer/nx-plugins#82]
## Describe the bug

Hello!, I have been using the playwright executor and I noticed that the screenshots are not being generated using toHaveScreenshot or toMatchSnapshot. According to playwright docs (https://playwright.dev/docs/test-snapshots) "On first execution, Playwright test will generate reference screenshots". I tested it in a repo using only playwright and it worked so I'm thinking that the issue is with the nx executor.

## To reproduce

I have this repo and screenshots are being generated on first execution
1. Clone this repo https://github.com/ealejandrootalvaro/playwright-repo
2. Follow README.md instructions

but in this other repo (using the nx executor) it doesn't work

1. Clone this repo https://github.com/ealejandrootalvaro/nx-repo
2. Follow README.md instructions

## Expected behaviour

On first execution, Playwright test will generate reference screenshots

## Additional context

I am willing to help in the implementation of the PR if we find that the problem is the executor, but I would need help understanding what is going on.

Thanks!

**Comment by andreacaldera** [comment]
Thanks for reporting this @ealejandrootalvaro, I'll have a look and work on a fix

**Comment by andreacaldera** [comment]
@ealejandrootalvaro did https://github.com/marksandspencer/nx-plugins/pull/84 help with this issue?
If not are you still keen on working on a PR?

**Comment by andreacaldera** [comment]
Closing as stale Issue
